server:
  port: 8081

spring:
  profiles:
    include: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teample_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.springframework.web: DEBUG


jwt:
  access-token-expiration: 3600000